services:
  postgres:
    image: postgres:15
    container_name: kontadoo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kontadoo_db
    ports:
      - "5432:5432"
    volumes:
      - kontadoo_pg_data:/var/lib/postgresql/data

volumes:
  kontadoo_pg_data:
